import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

async function render(path="/"){
  const workerUrl=new URL("../dist/server/index.js",import.meta.url);workerUrl.searchParams.set("test",`${process.pid}-${Date.now()}`);const {default:worker}=await import(workerUrl.href);
  return worker.fetch(new Request(`http://localhost${path}`,{headers:{accept:"text/html"}}),{ASSETS:{fetch:async()=>new Response("Not found",{status:404})}},{waitUntil(){},passThroughOnException(){}});
}

test("server renders the Sahaaya community entry",async()=>{const response=await render();assert.equal(response.status,200);assert.match(response.headers.get("content-type")??"",/^text\/html\b/i);const html=await response.text();assert.match(html,/<title>Sahaaya — Community Help Network<\/title>/i);assert.match(html,/SAHAAYA/);assert.match(html,/Sign in to request help/);assert.doesNotMatch(html,/codex-preview|Your site is taking shape/)});
test("production source includes privacy, identity, live-tracking, resilience, and accessibility safeguards",async()=>{const [platform,api,state,map,styles,adminAuth,adminRoute]=await Promise.all([readFile(new URL("../app/Platform.tsx",import.meta.url),"utf8"),readFile(new URL("../app/api/actions/route.ts",import.meta.url),"utf8"),readFile(new URL("../app/api/state/route.ts",import.meta.url),"utf8"),readFile(new URL("../app/LiveHelpMap.tsx",import.meta.url),"utf8"),readFile(new URL("../app/fixes.css",import.meta.url),"utf8"),readFile(new URL("../lib/admin-auth.ts",import.meta.url),"utf8"),readFile(new URL("../app/api/admin-auth/route.ts",import.meta.url),"utf8")]);assert.match(platform,/revealed\s+only to the helper whose offer you accept/);assert.match(platform,/navigator\.geolocation\.watchPosition/);assert.match(platform,/cancel_request/);assert.match(platform,/confirm_delivery/);assert.match(platform,/Admin dashboard/);assert.match(platform,/fetchStateWithRetry/);assert.match(platform,/sahaaya_accessibility/);assert.match(platform,/clientRequestId/);assert.match(platform,/new Notification/);assert.match(platform,/Administrator audit log/);assert.ok(platform.indexOf("new FormData(event.currentTarget)")<platform.indexOf("navigator.geolocation.getCurrentPosition"),"form values must be captured before awaiting location permission");assert.match(api,/Only the person who requested help can accept an offer/);assert.match(api,/Only the accepted helper can share delivery progress/);assert.match(api,/status='OPEN' AND accepted_by IS NULL/);assert.match(api,/Only the requester can confirm delivery/);assert.match(api,/requireAdminSession/);assert.match(api,/client_request_id/);assert.match(state,/delete output\.delivery_code/);assert.match(state,/scope/);assert.match(state,/auditLogs/);assert.match(map,/openstreetmap\.org/);assert.match(map,/marker\.on\("click"/);assert.match(map,/clusterPoints/);assert.match(adminAuth,/PBKDF2/);assert.match(adminAuth,/HttpOnly; Secure; SameSite=Strict/);assert.match(adminRoute,/change_password/);assert.match(adminRoute,/logout_all/);assert.match(styles,/@media\(max-width:760px\)/);assert.match(styles,/focus-visible/)});
test("professional motion includes branded loading, delivery success, and reduced-motion support",async()=>{const [platform,styles]=await Promise.all([readFile(new URL("../app/Platform.tsx",import.meta.url),"utf8"),readFile(new URL("../app/fixes.css",import.meta.url),"utf8")]);assert.match(platform,/function SahaayaIntro/);assert.match(platform,/function DeliverySuccess/);assert.match(platform,/payload\.action === "confirm_delivery"/);assert.match(styles,/@keyframes emblemRoll/);assert.match(styles,/@keyframes successCard/);assert.match(styles,/@media\(prefers-reduced-motion:reduce\)/)});
test("branded intro uses the deliberate six-second letter sequence",async()=>{const [platform,styles]=await Promise.all([readFile(new URL("../app/Platform.tsx",import.meta.url),"utf8"),readFile(new URL("../app/fixes.css",import.meta.url),"utf8")]);assert.match(platform,/accessibility\.reduceMotion \? 300 : 6000/);assert.doesNotMatch(platform,/accessibility\.reduceMotion \|\| window\.matchMedia/);assert.match(styles,/animation-duration:6s/);assert.match(styles,/html:not\(\.reduce-motion\) \.sahaaya-intro\{animation:introCurtain 6s/);assert.match(styles,/var\(--letter\)\*\.18s/);assert.match(styles,/0%,88%\{opacity:1/)});
