/* eslint-disable react-hooks/set-state-in-effect */
"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import "./security.css";
type Session={id:string;createdAt:string;expiresAt:string;lastUsedAt:string;userAgent:string;current:boolean};
const device=(agent:string)=>/Android|iPhone|Mobile/i.test(agent)?"Mobile browser":/Windows/i.test(agent)?"Windows browser":/Mac/i.test(agent)?"Mac browser":"Browser session";
export default function SecuritySettings({name,email}:{name:string;email:string}){const [sessions,setSessions]=useState<Session[]>([]),[notice,setNotice]=useState(""),[error,setError]=useState("");const load=async()=>{const response=await fetch("/api/auth/sessions",{cache:"no-store"});if(response.status===401){location.assign("/login");return}const data=await response.json() as {sessions?:Session[]};setSessions(data.sessions??[])};useEffect(()=>{void load()},[]);
  async function change(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");const form=event.currentTarget,payload=Object.fromEntries(new FormData(form).entries()),response=await fetch("/api/auth/change-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),data=await response.json() as {error?:string};if(!response.ok){setError(data.error||"Password could not be changed.");return}form.reset();setNotice("Password changed. Other devices were signed out.");await load()}
  async function revoke(id:string){await fetch("/api/auth/sessions",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});await load()}
  async function logoutAll(){await fetch("/api/auth/logout-all",{method:"POST"});location.assign("/")}
  return <main className="security-page"><header><Link href="/">← Back to Sahaaya</Link><div><p>ACCOUNT & PRIVACY</p><h1>Security settings</h1><span>{name} · {email}</span></div></header><div className="security-grid"><section><h2>Change password</h2><p>Changing your password keeps this device active and signs out every other device.</p><form onSubmit={change}><label>Current password<input name="currentPassword" type="password" autoComplete="current-password" required/></label><label>New password<input name="newPassword" type="password" autoComplete="new-password" minLength={10} maxLength={128} required/></label><label>Confirm new password<input name="confirmPassword" type="password" autoComplete="new-password" minLength={10} maxLength={128} required/></label>{error&&<p className="security-error" role="alert">{error}</p>}{notice&&<p className="security-success" role="status">{notice}</p>}<button>Update password</button></form></section><section><div className="security-title"><div><h2>Active sessions</h2><p>Devices currently signed into this account.</p></div><button className="danger-link" onClick={logoutAll}>Sign out everywhere</button></div><div className="session-list">{sessions.map(session=><article key={session.id}><i>{session.current?"●":"○"}</i><div><b>{device(session.userAgent)} {session.current&&<em>Current</em>}</b><span>Last active {new Date(session.lastUsedAt).toLocaleString()}</span><small>Signed in {new Date(session.createdAt).toLocaleString()}</small></div>{!session.current&&<button onClick={()=>revoke(session.id)}>Revoke</button>}</article>)}{!sessions.length&&<p>Loading active sessions…</p>}</div></section></div></main>}
