import { consumeRateLimit, db, timestamp } from "../../../lib/site-db";
import { auditAuth, clearSessionCookie, cookieToken, createUserSession, derivePassword, hashSecret, maybeCleanupExpiredSecurityState, newOpaqueToken, newPasswordSalt, normalizeEmail, passwordProblem, PASSWORD_ITERATIONS, requestThrottleKey, requireUser, safeEqual, sameOrigin, sessionCookie, sessionUser, validEmail } from "../../../lib/user-auth";
import { AuthorizationError, RateLimitError } from "../../../lib/errors";
import { emailDeliveryConfigured, publicOrigin, sendAccountEmail } from "../../../lib/email-delivery";

const jsonBody=async(request:Request)=>{try{return await request.json() as Record<string,unknown>}catch{return null}};
const securityHeaders={"Cache-Control":"private, no-store","X-Content-Type-Options":"nosniff"};
const invalidOrigin=()=>Response.json({error:"Cross-site requests are not allowed."},{status:403,headers:securityHeaders});
const safeUser=(user:{id:string;name:string;email:string;role:string;email_verified?:number})=>({id:user.id,name:user.name,email:user.email,role:user.role,emailVerified:!!user.email_verified});
const authError=(error:unknown)=>{const status=error instanceof RateLimitError?429:error instanceof AuthorizationError?403:500;return Response.json({error:status===429?"Too many attempts. Please wait and try again.":status===403?(error as Error).message:"Authentication could not be completed."},{status,headers:status===429?{...securityHeaders,"Retry-After":"60"}:securityHeaders})};

async function issueVerification(request:Request,user:{id:string;email:string}){
  if(!emailDeliveryConfigured())return false;
  const token=newOpaqueToken(),tokenHash=await hashSecret(token),createdAt=timestamp(),expiresAt=new Date(Date.now()+24*60*60_000).toISOString();
  await db().batch([db().prepare("UPDATE email_verification_tokens SET consumed_at=? WHERE user_id=? AND consumed_at IS NULL").bind(createdAt,user.id),db().prepare("INSERT INTO email_verification_tokens(id,user_id,token_hash,created_at,expires_at,consumed_at) VALUES(?,?,?,?,?,NULL)").bind(`verify-${crypto.randomUUID()}`,user.id,tokenHash,createdAt,expiresAt)]);
  const link=`${publicOrigin(request)}/verify-email?token=${encodeURIComponent(token)}`;
  const sent=await sendAccountEmail({to:user.email,subject:"Verify your Sahaaya account",text:`Verify your Sahaaya account within 24 hours: ${link}`,html:`<p>Verify your Sahaaya account within 24 hours.</p><p><a href="${link}">Verify Sahaaya account</a></p><p>If you did not create this account, ignore this message.</p>`});
  if(!sent)await db().prepare("DELETE FROM email_verification_tokens WHERE token_hash=?").bind(tokenHash).run();
  return sent;
}

export async function register(request:Request){try{
  if(!sameOrigin(request))return invalidOrigin();await maybeCleanupExpiredSecurityState();const body=await jsonBody(request);if(!body)return Response.json({error:"Invalid request body."},{status:400});
  const name=String(body.name??"").trim().replace(/\s+/g," "),email=normalizeEmail(String(body.email??"")),password=String(body.password??""),confirm=String(body.confirmPassword??"");
  if(String(body.website??"").trim())return Response.json({error:"Registration could not be completed."},{status:400,headers:securityHeaders});
  await consumeRateLimit(await requestThrottleKey(request,"auth-register",email||"unknown"),5,60*60_000);
  if(name.length<2||name.length>100)return Response.json({error:"Enter your full name."},{status:400});if(!validEmail(email))return Response.json({error:"Enter a valid email address."},{status:400});const problem=passwordProblem(password);if(problem)return Response.json({error:problem},{status:400});if(password!==confirm)return Response.json({error:"Passwords do not match."},{status:400});
  const existing=await db().prepare("SELECT id,password_hash FROM users WHERE email=? COLLATE NOCASE").bind(email).first<{id:string;password_hash:string|null}>();if(existing)return Response.json({error:existing.password_hash?"An account with this email already exists.":"This email belongs to a legacy Sahaaya account. Use verified account recovery when email delivery is enabled."},{status:409});
  const id=`usr-${crypto.randomUUID()}`,salt=newPasswordSalt(),hash=await derivePassword(password,salt),now=timestamp();
  try{await db().prepare("INSERT INTO users(id,email,name,password_hash,password_salt,password_iterations,role,email_verified,created_at,updated_at) VALUES(?,?,?,?,?,?,'RESIDENT',0,?,?)").bind(id,email,name,hash,salt,PASSWORD_ITERATIONS,now,now).run()}catch{return Response.json({error:"An account with this email already exists."},{status:409})}
  const session=await createUserSession(id,request.headers.get("user-agent")??"Unknown device");await auditAuth(id,"REGISTER");const verificationSent=await issueVerification(request,{id,email});
  return Response.json({user:{id,name,email,role:"RESIDENT",emailVerified:false},verificationSent},{status:201,headers:{...securityHeaders,"Set-Cookie":sessionCookie(session.token)}});
}catch(error){return authError(error)}}

export async function claimLegacyAccount(request:Request){try{
  if(!sameOrigin(request))return invalidOrigin();const body=await jsonBody(request);if(!body)return Response.json({error:"Invalid request body."},{status:400});
  const providerId=String(request.headers.get("oai-authenticated-user-id")??"").trim(),providerEmail=normalizeEmail(String(request.headers.get("oai-authenticated-user-email")??"")),password=String(body.password??""),confirm=String(body.confirmPassword??"");
  if(!providerId||!validEmail(providerEmail))return Response.json({error:"Open this page while signed in with the original account that created your Sahaaya profile."},{status:401,headers:securityHeaders});
  await consumeRateLimit(`auth-legacy-claim:${providerId}`,5,60*60_000);const problem=passwordProblem(password);if(problem)return Response.json({error:problem},{status:400});if(password!==confirm)return Response.json({error:"Passwords do not match."},{status:400});
  const user=await db().prepare("SELECT id,email,name,role,email_verified,blocked_at,password_hash FROM users WHERE id=? AND email=? COLLATE NOCASE").bind(providerId,providerEmail).first<{id:string;email:string;name:string;role:string;email_verified:number;blocked_at:string|null;password_hash:string|null}>();
  if(!user)return Response.json({error:"No matching legacy Sahaaya account was found. Create a new account instead."},{status:404,headers:securityHeaders});if(user.blocked_at)return Response.json({error:"This account is currently restricted."},{status:403,headers:securityHeaders});if(user.password_hash)return Response.json({error:"This account is already activated. Sign in with its Sahaaya password."},{status:409,headers:securityHeaders});
  const salt=newPasswordSalt(),hash=await derivePassword(password,salt),now=timestamp();const updated=await db().prepare("UPDATE users SET password_hash=?,password_salt=?,password_iterations=?,updated_at=? WHERE id=? AND password_hash IS NULL").bind(hash,salt,PASSWORD_ITERATIONS,now,user.id).run();if(!updated.meta.changes)return Response.json({error:"This account was already activated. Sign in with its Sahaaya password."},{status:409,headers:securityHeaders});
  await db().prepare("DELETE FROM user_sessions WHERE user_id=?").bind(user.id).run();const session=await createUserSession(user.id,request.headers.get("user-agent")??"Unknown device");await auditAuth(user.id,"LEGACY_ACCOUNT_CLAIMED");return Response.json({user:safeUser(user)},{headers:{...securityHeaders,"Set-Cookie":sessionCookie(session.token)}});
}catch(error){return authError(error)}}

export async function login(request:Request){try{
  if(!sameOrigin(request))return invalidOrigin();await maybeCleanupExpiredSecurityState();const body=await jsonBody(request);if(!body)return Response.json({error:"Invalid request body."},{status:400});const email=normalizeEmail(String(body.email??"")),password=String(body.password??"");
  await consumeRateLimit(await requestThrottleKey(request,"auth-login",email||"unknown"),8,15*60_000);const user=await db().prepare("SELECT id,email,name,role,email_verified,blocked_at,password_hash,password_salt,password_iterations FROM users WHERE email=? COLLATE NOCASE").bind(email).first<{id:string;email:string;name:string;role:string;email_verified:number;blocked_at:string|null;password_hash:string|null;password_salt:string|null;password_iterations:number|null}>();
  const salt=user?.password_salt??"00000000000000000000000000000000",candidate=await derivePassword(password,salt,user?.password_iterations??PASSWORD_ITERATIONS);if(!user||!user.password_hash||!safeEqual(candidate,user.password_hash)){if(user)await auditAuth(user.id,"LOGIN_FAILURE");return Response.json({error:"Invalid email or password."},{status:401,headers:securityHeaders})}if(user.blocked_at)return Response.json({error:"This account is currently restricted."},{status:403,headers:securityHeaders});
  const session=await createUserSession(user.id,request.headers.get("user-agent")??"Unknown device");await auditAuth(user.id,"LOGIN_SUCCESS");return Response.json({user:safeUser(user)},{headers:{...securityHeaders,"Set-Cookie":sessionCookie(session.token)}});
}catch(error){return authError(error)}}

export async function me(request:Request){try{const user=await sessionUser(request.headers);return user?Response.json({user:safeUser(user)},{headers:securityHeaders}):Response.json({user:null},{status:401,headers:securityHeaders})}catch(error){return authError(error)}}
export async function logout(request:Request){try{if(!sameOrigin(request))return invalidOrigin();const user=await sessionUser(request.headers),token=cookieToken(request.headers);if(token)await db().prepare("DELETE FROM user_sessions WHERE token_hash=?").bind(await hashSecret(token)).run();if(user)await auditAuth(user.id,"LOGOUT");return Response.json({ok:true},{headers:{...securityHeaders,"Set-Cookie":clearSessionCookie()}})}catch{return Response.json({ok:true},{headers:{...securityHeaders,"Set-Cookie":clearSessionCookie()}})}}
export async function logoutAll(request:Request){try{if(!sameOrigin(request))return invalidOrigin();const user=await requireUser(request.headers);await db().prepare("DELETE FROM user_sessions WHERE user_id=?").bind(user.id).run();await auditAuth(user.id,"LOGOUT_ALL");return Response.json({ok:true},{headers:{...securityHeaders,"Set-Cookie":clearSessionCookie()}})}catch(error){return authError(error)}}

export async function sessions(request:Request){try{const user=await requireUser(request.headers),current=await hashSecret(cookieToken(request.headers)??"");const rows=await db().prepare("SELECT id,token_hash,created_at,expires_at,last_used_at,user_agent FROM user_sessions WHERE user_id=? AND expires_at>? ORDER BY last_used_at DESC").bind(user.id,timestamp()).all<Record<string,string>>();return Response.json({sessions:rows.results.map(row=>({id:row.id,createdAt:row.created_at,expiresAt:row.expires_at,lastUsedAt:row.last_used_at,userAgent:row.user_agent,current:safeEqual(row.token_hash,current)}))},{headers:securityHeaders})}catch(error){return authError(error)}}
export async function revokeSession(request:Request){try{if(!sameOrigin(request))return invalidOrigin();const user=await requireUser(request.headers),body=await jsonBody(request),id=String(body?.id??"");const currentHash=await hashSecret(cookieToken(request.headers)??"");const target=await db().prepare("SELECT token_hash FROM user_sessions WHERE id=? AND user_id=?").bind(id,user.id).first<{token_hash:string}>();if(!target)return Response.json({error:"Session not found."},{status:404});if(safeEqual(target.token_hash,currentHash))return Response.json({error:"Use Sign out to end the current session."},{status:409});await db().prepare("DELETE FROM user_sessions WHERE id=? AND user_id=?").bind(id,user.id).run();await auditAuth(user.id,"SESSION_REVOKED",{sessionId:id});return Response.json({ok:true})}catch(error){return authError(error)}}

export async function changePassword(request:Request){try{if(!sameOrigin(request))return invalidOrigin();const user=await requireUser(request.headers),body=await jsonBody(request);if(!body)return Response.json({error:"Invalid request body."},{status:400});const current=String(body.currentPassword??""),next=String(body.newPassword??""),confirm=String(body.confirmPassword??"");const problem=passwordProblem(next);if(problem)return Response.json({error:problem},{status:400});if(next!==confirm)return Response.json({error:"Passwords do not match."},{status:400});await consumeRateLimit(`auth-password:${user.id}`,5,60*60_000);const credential=await db().prepare("SELECT password_hash,password_salt,password_iterations FROM users WHERE id=?").bind(user.id).first<{password_hash:string|null;password_salt:string|null;password_iterations:number|null}>();if(!credential?.password_hash||!credential.password_salt||!safeEqual(await derivePassword(current,credential.password_salt,credential.password_iterations??PASSWORD_ITERATIONS),credential.password_hash))return Response.json({error:"Current password is incorrect."},{status:401});const salt=newPasswordSalt(),hash=await derivePassword(next,salt),currentTokenHash=await hashSecret(cookieToken(request.headers)??"");await db().batch([db().prepare("UPDATE users SET password_hash=?,password_salt=?,password_iterations=?,updated_at=? WHERE id=?").bind(hash,salt,PASSWORD_ITERATIONS,timestamp(),user.id),db().prepare("DELETE FROM user_sessions WHERE user_id=? AND token_hash<>?").bind(user.id,currentTokenHash)]);await auditAuth(user.id,"PASSWORD_CHANGED");return Response.json({ok:true})}catch(error){return authError(error)}}

export async function forgotPassword(request:Request){try{if(!sameOrigin(request))return invalidOrigin();const body=await jsonBody(request),email=normalizeEmail(String(body?.email??""));await consumeRateLimit(await requestThrottleKey(request,"auth-reset",email||"unknown"),4,60*60_000);const configured=emailDeliveryConfigured();const user=validEmail(email)?await db().prepare("SELECT id,email FROM users WHERE email=? COLLATE NOCASE AND password_hash IS NOT NULL AND blocked_at IS NULL").bind(email).first<{id:string;email:string}>():null;if(configured&&user){const token=newOpaqueToken(),tokenHash=await hashSecret(token),createdAt=timestamp(),expiresAt=new Date(Date.now()+30*60_000).toISOString();await db().batch([db().prepare("UPDATE password_reset_tokens SET consumed_at=? WHERE user_id=? AND consumed_at IS NULL").bind(createdAt,user.id),db().prepare("INSERT INTO password_reset_tokens(id,user_id,token_hash,created_at,expires_at,consumed_at) VALUES(?,?,?,?,?,NULL)").bind(`reset-${crypto.randomUUID()}`,user.id,tokenHash,createdAt,expiresAt)]);const link=`${publicOrigin(request)}/reset-password?token=${encodeURIComponent(token)}`;const sent=await sendAccountEmail({to:user.email,subject:"Reset your Sahaaya password",text:`Reset your Sahaaya password within 30 minutes: ${link}`,html:`<p>A password reset was requested for your Sahaaya account.</p><p><a href="${link}">Reset password</a></p><p>This link expires in 30 minutes. If you did not request it, ignore this message.</p>`});if(!sent)await db().prepare("DELETE FROM password_reset_tokens WHERE token_hash=?").bind(tokenHash).run()}return Response.json({ok:true,deliveryConfigured:configured,message:configured?"If a matching account exists, a recovery email will arrive shortly.":"Password recovery email is not configured yet. No email was sent."},{status:202,headers:securityHeaders})}catch(error){return authError(error)}}
export async function resetPassword(request:Request){try{if(!sameOrigin(request))return invalidOrigin();const body=await jsonBody(request),token=String(body?.token??""),password=String(body?.password??""),confirm=String(body?.confirmPassword??"");const problem=passwordProblem(password);if(problem)return Response.json({error:problem},{status:400});if(password!==confirm)return Response.json({error:"Passwords do not match."},{status:400});const tokenHash=await hashSecret(token),row=await db().prepare("SELECT id,user_id FROM password_reset_tokens WHERE token_hash=? AND consumed_at IS NULL AND expires_at>?").bind(tokenHash,timestamp()).first<{id:string;user_id:string}>();if(!row)return Response.json({error:"This reset link is invalid or expired."},{status:400});const salt=newPasswordSalt(),hash=await derivePassword(password,salt),now=timestamp();await db().batch([db().prepare("UPDATE users SET password_hash=?,password_salt=?,password_iterations=?,updated_at=? WHERE id=?").bind(hash,salt,PASSWORD_ITERATIONS,now,row.user_id),db().prepare("UPDATE password_reset_tokens SET consumed_at=? WHERE id=?").bind(now,row.id),db().prepare("DELETE FROM user_sessions WHERE user_id=?").bind(row.user_id)]);await auditAuth(row.user_id,"PASSWORD_RESET");return Response.json({ok:true})}catch(error){return authError(error)}}
export async function verifyEmail(request:Request){try{if(!sameOrigin(request))return invalidOrigin();const body=await jsonBody(request),tokenHash=await hashSecret(String(body?.token??"")),now=timestamp();const row=await db().prepare("SELECT id,user_id FROM email_verification_tokens WHERE token_hash=? AND consumed_at IS NULL AND expires_at>?").bind(tokenHash,now).first<{id:string;user_id:string}>();if(!row)return Response.json({error:"This verification link is invalid or expired."},{status:400});await db().batch([db().prepare("UPDATE users SET email_verified=1,updated_at=? WHERE id=?").bind(now,row.user_id),db().prepare("UPDATE email_verification_tokens SET consumed_at=? WHERE user_id=? AND consumed_at IS NULL").bind(now,row.user_id),db().prepare("INSERT INTO audit_logs(actor_id,action,entity_type,entity_id,metadata,created_at) VALUES(?,'EMAIL_VERIFIED','USER',?,'{}',?)").bind(row.user_id,row.user_id,now)]);return Response.json({ok:true})}catch(error){return authError(error)}}

export async function resendVerification(request:Request){try{if(!sameOrigin(request))return invalidOrigin();const user=await requireUser(request.headers);await consumeRateLimit(await requestThrottleKey(request,"auth-verify",user.email),3,60*60_000);if(user.email_verified)return Response.json({ok:true,message:"Your email is already verified."},{headers:securityHeaders});const sent=await issueVerification(request,{id:user.id,email:user.email});return Response.json({ok:sent,message:sent?"A new verification email was sent.":"Email verification is not configured yet."},{status:sent?202:503,headers:securityHeaders})}catch(error){return authError(error)}}
