/* eslint-disable @typescript-eslint/no-explicit-any, jsx-a11y/no-static-element-interactions, jsx-a11y/no-noninteractive-element-interactions */
"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";

type Row=Record<string,any>;
type State={user:Row;requests:Row[];events:Row[];volunteers:Row[];organizations:Row[];resources:Row[];notifications:Row[];reports:Row[];activity:Row[];metrics:Row};
const empty:State={user:{},requests:[],events:[],volunteers:[],organizations:[],resources:[],notifications:[],reports:[],activity:[],metrics:{}};
const roles=["Resident","Volunteer","Organization","Admin"];
const categories=["ALL","FOOD","WATER","MEDICAL","SHELTER","RESCUE","CLOTHES","TRANSPORT","OTHER"];
const statuses=["OPEN","ACCEPTED","VOLUNTEER_ASSIGNED","IN_PROGRESS","RESOLVED","CANCELLED"];

function human(value:string){return value?.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,(letter)=>letter.toUpperCase())}
function ago(value:string){const minutes=Math.max(1,Math.floor((Date.now()-new Date(value).getTime())/60000));return minutes<60?`${minutes}m ago`:minutes<1440?`${Math.floor(minutes/60)}h ago`:`${Math.floor(minutes/1440)}d ago`}

export default function Platform(){
  const [data,setData]=useState<State>(empty);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [toast,setToast]=useState("");
  const [view,setView]=useState("overview");const [role,setRole]=useState("Organization");const [q,setQ]=useState("");const [category,setCategory]=useState("ALL");const [status,setStatus]=useState("ALL");
  const [selected,setSelected]=useState<Row|null>(null);const [showRequest,setShowRequest]=useState(false);const [showNotifications,setShowNotifications]=useState(false);
  const load=useCallback(async()=>{setLoading(true);try{const params=new URLSearchParams({q,category,status});const response=await fetch(`/api/state?${params}`,{cache:"no-store"});if(!response.ok)throw new Error();setData(await response.json());setError("")}catch{setError("Coordination data is temporarily unavailable. Please retry.")}finally{setLoading(false)}},[q,category,status]);
  useEffect(()=>{const timer=setTimeout(load,200);return()=>clearTimeout(timer)},[load]);
  async function act(payload:Row,success:string){try{const response=await fetch("/api/actions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw new Error(result.error);setToast(success);await load();return result}catch(reason){setToast(reason instanceof Error?reason.message:"Action failed safely.");return null}}
  const active=data.requests.filter((item)=>!["RESOLVED","CANCELLED"].includes(item.status));const critical=active.filter((item)=>item.urgency==="CRITICAL");const available=data.volunteers.filter((item)=>item.available);const unread=data.notifications.filter((item)=>!item.read_at);
  const menu=[{id:"overview",label:"Response overview",icon:"⌂"},{id:"requests",label:"All requests",icon:"◎"},{id:"map",label:"Live map",icon:"⌖"},{id:"volunteer",label:"Volunteer center",icon:"♙"},{id:"organization",label:"Organization hub",icon:"◇"},{id:"resources",label:"Resources",icon:"▦"},{id:"admin",label:"Admin control",icon:"⚙"}];
  return <main className="platform-shell">
    <aside className="sidebar"><button className="side-brand" onClick={()=>setView("overview")}><span>✦</span><b>SAHAAYA<small>Response Network</small></b></button><div className="side-event"><i/> <span><small>ACTIVE EVENT</small>Bengaluru Flood Response</span></div><nav className="side-nav" aria-label="Workspace navigation">{menu.map((item)=><button key={item.id} className={view===item.id?"active":""} onClick={()=>setView(item.id)}><i>{item.icon}</i>{item.label}</button>)}</nav><div className="side-section"><small>YOUR WORKSPACE</small><button onClick={()=>setView("notifications")}><i>●</i> Notifications {unread.length>0&&<b>{unread.length}</b>}</button><button onClick={()=>setView("profile")}><i>◌</i> Profile & settings</button></div><div className="system-state"><i/><span><b>All systems operational</b><small>Last synchronized just now</small></span></div></aside>
    <section className="workspace">
      <header className="workspace-top"><button className="mobile-brand" onClick={()=>setView("overview")}>✦ SAHAAYA</button><div className="crumb"><small>SAHAAYA / {role.toUpperCase()}</small><b>{menu.find((item)=>item.id===view)?.label??human(view)}</b></div><div className="top-actions"><label>Workspace<select value={role} onChange={(e)=>{setRole(e.target.value);setToast(`${e.target.value} workspace loaded`)}}>{roles.map((item)=><option key={item}>{item}</option>)}</select></label><button className="top-note" onClick={()=>setShowNotifications(!showNotifications)}>●{unread.length>0&&<span>{unread.length}</span>}</button><button className="avatar">{(data.user.name||"AK").split(" ").map((part:string)=>part[0]).join("").slice(0,2)}</button></div></header>
      {showNotifications&&<NotificationPanel items={data.notifications} close={()=>setShowNotifications(false)} read={()=>act({action:"read_notifications"},"Notifications marked as read")}/>} 
      <div className="workspace-content">
        {error&&<div className="error-banner" role="alert">{error}<button onClick={load}>Retry</button></div>}
        {loading?<Loading/>:<>
          {view==="overview"&&<Overview data={data} active={active} critical={critical} available={available} openRequest={()=>setShowRequest(true)} select={(item)=>setSelected(item)} navigate={setView}/>} 
          {view==="requests"&&<Requests data={data} q={q} setQ={setQ} category={category} setCategory={setCategory} status={status} setStatus={setStatus} select={setSelected} openRequest={()=>setShowRequest(true)}/>} 
          {view==="map"&&<MapView requests={data.requests} setCategory={setCategory} category={category} select={setSelected}/>} 
          {view==="volunteer"&&<VolunteerView data={data} active={active} act={act} select={setSelected}/>} 
          {view==="organization"&&<OrganizationView data={data} act={act} select={setSelected}/>} 
          {view==="resources"&&<ResourcesView resources={data.resources} act={act}/>} 
          {view==="admin"&&<AdminView data={data} act={act}/>} 
          {view==="notifications"&&<NotificationsView items={data.notifications} read={()=>act({action:"read_notifications"},"Notifications marked as read")}/>} 
          {view==="profile"&&<Profile user={data.user} role={role}/>} 
        </>}
      </div>
    </section>
    <button className="floating-help" onClick={()=>setShowRequest(true)}>＋ <span>Request help</span></button>
    {showRequest&&<RequestModal events={data.events} close={()=>setShowRequest(false)} submit={async(payload,file)=>{const result=await act({action:"create_request",...payload},"Emergency request created and matching started");if(result&&file?.size){const upload=new FormData();upload.set("file",file);upload.set("requestId",result.id);const response=await fetch("/api/uploads",{method:"POST",body:upload});if(!response.ok)setToast((await response.json()).error||"Request created, but the image could not be uploaded.")}if(result)setShowRequest(false)}}/>}
    {selected&&<RequestDetail item={selected} data={data} close={()=>setSelected(null)} act={act}/>} 
    {toast&&<div className="global-toast" role="status">{toast}<button onClick={()=>setToast("")}>×</button></div>}
  </main>
}

function Loading(){return <div className="loading-state"><span/><span/><span/><p>Synchronizing response network…</p></div>}

function PageHead({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action?:React.ReactNode}){return <div className="page-head"><div><p className="overline">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div>{action}</div>}

function Overview({data,active,critical,available,openRequest,select,navigate}:{data:State;active:Row[];critical:Row[];available:Row[];openRequest:()=>void;select:(r:Row)=>void;navigate:(v:string)=>void}){return <>
  <PageHead eyebrow="LIVE RESPONSE OVERVIEW · UPDATED JUST NOW" title="Every request. One coordinated response." description="A shared command center for residents, volunteers, and verified relief organizations." action={<div className="head-actions"><button className="soft-btn" onClick={()=>window.print()}>↗ Situation report</button><button className="solid-btn" onClick={openRequest}>＋ Request help</button></div>}/>
  <div className="stat-grid"><Stat icon="!" tone="red" label="Active requests" value={active.length} note={`${active.filter(r=>r.status==="OPEN").length} awaiting acceptance`}/><Stat icon="◆" tone="amber" label="Critical requests" value={critical.length} note="Prioritized for dispatch"/><Stat icon="✓" tone="green" label="Requests resolved" value={data.requests.filter(r=>r.status==="RESOLVED").length} note="Full timeline retained"/><Stat icon="●" tone="blue" label="Available volunteers" value={available.length} note={`${data.volunteers.length} registered`}/><Stat icon="◇" tone="purple" label="Organizations" value={data.organizations.filter(o=>o.verified).length} note="Verified partners"/></div>
  <div className="overview-grid"><MapCard requests={active.slice(0,12)} select={select}/><section className="surface priority-card"><CardHead eyebrow="NEEDS ATTENTION" title="Priority queue" action={<button onClick={()=>navigate("requests")}>View all →</button>}/><div className="priority-list">{active.slice(0,5).map(item=><RequestRow key={item.id} item={item} select={select}/>)}</div><div className="privacy-strip">⌾ <b>Privacy protected</b><span>Approximate areas are public. Contact details appear only after verified assignment.</span></div></section></div>
  <div className="two-grid"><ResourceSummary resources={data.resources} navigate={()=>navigate("resources")}/><Activity items={data.activity}/></div>
  </>}

function Stat({icon,tone,label,value,note}:{icon:string;tone:string;label:string;value:number;note:string}){return <article className="stat-card"><i className={tone}>{icon}</i><div><p>{label}</p><strong>{value}</strong><small>{note}</small></div></article>}
function CardHead({eyebrow,title,action}:{eyebrow:string;title:string;action?:React.ReactNode}){return <div className="card-head"><div><p className="overline">{eyebrow}</p><h2>{title}</h2></div>{action}</div>}
function Badge({value}:{value:string}){return <span className={`badge ${value.toLowerCase()}`}>{human(value)}</span>}
function RequestRow({item,select}:{item:Row;select:(r:Row)=>void}){return <button className="request-line" onClick={()=>select(item)}><i className={item.urgency.toLowerCase()}/><span><b>{human(item.category)}</b><small>{item.id} · {item.public_area}</small></span><Badge value={item.urgency}/><span className="people"><b>{item.people_count}</b><small>people</small></span><time>{ago(item.created_at)}</time><em>›</em></button>}

function MapCard({requests,select}:{requests:Row[];select:(r:Row)=>void}){return <section className="surface map-panel"><CardHead eyebrow="OPERATIONAL VIEW" title="Live response map" action={<span className="safe-map">⌾ Approximate locations</span>}/><div className="live-map"><span className="map-road one"/><span className="map-road two"/><span className="map-road three"/><b className="area a">WHITEFIELD</b><b className="area b">BELLANDUR</b><b className="area c">MARATHAHALLI</b>{requests.map((item,index)=><button key={item.id} className={`map-pin ${item.urgency.toLowerCase()}`} style={{left:`${18+(index*17)%68}%`,top:`${18+(index*23)%65}%`}} onClick={()=>select(item)} aria-label={`${item.urgency} ${item.category} request in ${item.public_area}`}>{item.people_count}</button>)}<div className="map-key"><span><i className="critical"/>Critical</span><span><i className="urgent"/>Urgent</span><span><i className="normal"/>Normal</span></div></div></section>}

function Requests({data,q,setQ,category,setCategory,status,setStatus,select,openRequest}:{data:State;q:string;setQ:(v:string)=>void;category:string;setCategory:(v:string)=>void;status:string;setStatus:(v:string)=>void;select:(r:Row)=>void;openRequest:()=>void}){return <><PageHead eyebrow="REQUEST OPERATIONS" title="Help request registry" description="Search, triage, assign, and follow every request without exposing sensitive contact details." action={<button className="solid-btn" onClick={openRequest}>＋ New request</button>}/><section className="surface filter-bar"><label className="search">⌕<input value={q} onChange={(e)=>setQ(e.target.value)} placeholder="Search ID, area, or description"/></label><label>Category<select value={category} onChange={(e)=>setCategory(e.target.value)}>{categories.map(v=><option key={v}>{human(v)}</option>)}</select></label><label>Status<select value={status} onChange={(e)=>setStatus(e.target.value)}><option value="ALL">All statuses</option>{statuses.map(v=><option key={v}>{human(v)}</option>)}</select></label><button className="soft-btn" onClick={()=>{setQ("");setCategory("ALL");setStatus("ALL")}}>Clear filters</button></section><section className="surface data-card"><div className="table-title"><b>{data.requests.length} requests</b><small>Sorted by urgency, then newest</small></div>{data.requests.length?<div className="request-table"><div className="tr th"><span>Request</span><span>Area</span><span>People</span><span>Urgency</span><span>Status</span><span>Created</span><span/></div>{data.requests.map(item=><button className="tr" key={item.id} onClick={()=>select(item)}><span><b>{human(item.category)}</b><small>{item.id}</small></span><span>{item.public_area}</span><span>{item.people_count}</span><span><Badge value={item.urgency}/></span><span><Badge value={item.status}/></span><span>{ago(item.created_at)}</span><span>›</span></button>)}</div>:<Empty title="No requests match these filters" text="Clear one or more filters to broaden the search."/>}</section></>}

function MapView({requests,setCategory,category,select}:{requests:Row[];setCategory:(v:string)=>void;category:string;select:(r:Row)=>void}){const shown=category==="ALL"?requests:requests.filter(r=>r.category===category);return <><PageHead eyebrow="PRIVACY-SAFE GEOGRAPHY" title="Disaster response map" description="Coordinate by approximate service area. Exact addresses remain protected."/><div className="map-layout"><section className="surface map-filters"><b>Map filters</b><label>Help category<select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(v=><option key={v}>{human(v)}</option>)}</select></label><div className="legend-block"><small>URGENCY</small><span><i className="critical"/>Critical</span><span><i className="urgent"/>Urgent</span><span><i className="normal"/>Normal</span></div><p>⌾ Marker positions are deliberately offset within each area to protect residents.</p></section><section className="surface full-map"><div className="live-map">{[1,2,3,4].map(n=><span key={n} className={`map-road road-${n}`}/>)}<b className="area a">WHITEFIELD</b><b className="area b">BELLANDUR</b><b className="area c">MARATHAHALLI</b>{shown.map((item,index)=><button key={item.id} className={`map-pin ${item.urgency.toLowerCase()}`} style={{left:`${12+(index*13)%76}%`,top:`${12+(index*19)%72}%`}} onClick={()=>select(item)}>{item.people_count}</button>)}</div></section></div></>}

function VolunteerView({data,active,act,select}:{data:State;active:Row[];act:(p:Row,s:string)=>Promise<any>;select:(r:Row)=>void}){const volunteer=data.volunteers[0];const matches=active.filter(item=>JSON.parse(volunteer?.skills||"[]").includes(item.category)||JSON.parse(volunteer?.areas||"[]").includes(item.public_area));const assigned=data.requests.filter(item=>item.assigned_volunteer_id===volunteer?.user_id);return <><PageHead eyebrow="VOLUNTEER OPERATIONS" title="Volunteer response center" description="Discover suitable nearby requests, manage availability, and complete active tasks safely." action={<label className="availability"><span className={volunteer?.available?"on":""}/><input type="checkbox" checked={!!volunteer?.available} onChange={(e)=>act({action:"availability",volunteerId:volunteer.user_id,available:e.target.checked},e.target.checked?"You are now available":"Availability paused")}/>{volunteer?.available?"Available":"Unavailable"}</label>}/><div className="mini-stats"><article><small>NEARBY MATCHES</small><b>{matches.length}</b></article><article><small>ACTIVE TASKS</small><b>{assigned.filter(r=>r.status!=="RESOLVED").length}</b></article><article><small>COMPLETED TASKS</small><b>{volunteer?.completed_tasks||0}</b></article><article><small>PRIMARY AREAS</small><b className="words">{JSON.parse(volunteer?.areas||"[]").join(", ")}</b></article></div><div className="two-grid align-start"><section className="surface"><CardHead eyebrow="SMART MATCHING" title="Recommended requests"/><div className="priority-list">{matches.length?matches.slice(0,8).map(item=><div className="match-row" key={item.id}><RequestRow item={item} select={select}/><button className="solid-btn small" onClick={()=>act({action:"accept_request",id:item.id},`${item.id} accepted`)}>Accept</button></div>):<Empty title="No suitable requests right now" text="Keep availability on and new matches will appear automatically."/>}</div></section><section className="surface"><CardHead eyebrow="YOUR WORK" title="Active and completed tasks"/><div className="task-list">{assigned.length?assigned.map(item=><button key={item.id} onClick={()=>select(item)}><Badge value={item.status}/><b>{human(item.category)} · {item.public_area}</b><small>{item.id} · {item.people_count} people</small></button>):<Empty title="No assigned tasks" text="Accepted and assigned requests will appear here."/>}</div></section></div></>}

function OrganizationView({data,act,select}:{data:State;act:(p:Row,s:string)=>Promise<any>;select:(r:Row)=>void}){const open=data.requests.filter(r=>r.status==="OPEN");const accepted=data.requests.filter(r=>["ACCEPTED","VOLUNTEER_ASSIGNED","IN_PROGRESS"].includes(r.status));return <><PageHead eyebrow="VERIFIED PARTNER HUB" title="Organization operations" description="Triage requests, assign qualified volunteers, and coordinate resources from one operational queue."/><div className="mini-stats"><article><small>OPEN REQUESTS</small><b>{open.length}</b></article><article><small>IN PROGRESS</small><b>{accepted.length}</b></article><article><small>AVAILABLE VOLUNTEERS</small><b>{data.volunteers.filter(v=>v.available).length}</b></article><article><small>RESOURCE TYPES</small><b>{data.resources.length}</b></article></div><div className="org-grid"><section className="surface"><CardHead eyebrow="TRIAGE" title="Unaccepted requests"/><div className="org-queue">{open.slice(0,10).map(item=><div key={item.id}><button className="org-request" onClick={()=>select(item)}><Badge value={item.urgency}/><span><b>{human(item.category)} for {item.people_count}</b><small>{item.id} · {item.public_area} · {ago(item.created_at)}</small></span></button><button className="solid-btn small" onClick={()=>act({action:"accept_request",id:item.id},`${item.id} accepted by organization`)}>Accept</button></div>)}</div></section><section className="surface"><CardHead eyebrow="ASSIGNMENTS" title="Dispatch volunteer"/><div className="assignment-list">{accepted.slice(0,8).map(item=><div key={item.id}><span><b>{item.id}</b><small>{human(item.category)} · {item.public_area}</small></span>{item.assigned_volunteer_id?<Badge value="VOLUNTEER_ASSIGNED"/>:<select defaultValue="" onChange={(e)=>e.target.value&&act({action:"assign_volunteer",id:item.id,volunteerId:e.target.value},"Volunteer assigned and notified")}><option value="" disabled>Assign volunteer</option>{data.volunteers.filter(v=>v.available).map(v=><option key={v.user_id} value={v.user_id}>{v.name}</option>)}</select>}</div>)}</div></section></div></>}

function ResourcesView({resources,act}:{resources:Row[];act:(p:Row,s:string)=>Promise<any>}){const [adjust,setAdjust]=useState<Row|null>(null);const [adding,setAdding]=useState(false);return <><PageHead eyebrow="RESOURCE ACCOUNTABILITY" title="Relief inventory" description="Track available stock and record every distribution without allowing negative balances." action={<button className="solid-btn" onClick={()=>setAdding(true)}>＋ Add resource</button>}/><section className="resource-board">{resources.map(item=><article className="resource-tile" key={item.id}><span className={`resource-big ${item.category.toLowerCase()}`}>{item.category==="MEDICAL"?"+":item.category==="SHELTER"?"⌂":"◉"}</span><div><p>{human(item.category)}</p><h3>{item.name}</h3><strong>{item.quantity.toLocaleString()} <small>{item.unit}</small></strong><span className="stock-track"><i style={{width:`${Math.min(100,Math.max(12,item.quantity/50))}%`}}/></span><small>{item.organization_name} · updated {ago(item.updated_at)}</small></div><button className="soft-btn" onClick={()=>setAdjust(item)}>Adjust</button></article>)}</section>{adjust&&<AdjustResource item={adjust} close={()=>setAdjust(null)} submit={async(delta,note)=>{await act({action:"adjust_resource",id:adjust.id,delta,note},"Resource ledger updated");setAdjust(null)}}/>}{adding&&<AddResource close={()=>setAdding(false)} submit={async(payload)=>{const result=await act({action:"add_resource",...payload},"Resource added to inventory");if(result)setAdding(false)}}/>}</>}
function ResourceSummary({resources,navigate}:{resources:Row[];navigate:()=>void}){return <section className="surface"><CardHead eyebrow="SUPPLY READINESS" title="Available resources" action={<button onClick={navigate}>Manage inventory →</button>}/><div className="resource-summary">{resources.slice(0,4).map(item=><article key={item.id}><i className={item.category.toLowerCase()}>{item.category==="MEDICAL"?"+":"◉"}</i><span><b>{item.name}</b><strong>{item.quantity.toLocaleString()}</strong><small>{item.unit} · {item.organization_name}</small></span></article>)}</div></section>}

function AdminView({data,act}:{data:State;act:(p:Row,s:string)=>Promise<any>}){const [showEvent,setShowEvent]=useState(false);return <><PageHead eyebrow="SYSTEM GOVERNANCE" title="Administration control room" description="Review reports, verify partners, monitor activity, and manage events without automated fraud judgments." action={<button className="solid-btn" onClick={()=>setShowEvent(true)}>＋ Create disaster event</button>}/><div className="mini-stats"><article><small>PENDING REPORTS</small><b>{data.reports.filter(r=>r.status==="PENDING").length}</b></article><article><small>UNVERIFIED PARTNERS</small><b>{data.organizations.filter(o=>!o.verified).length}</b></article><article><small>REGISTERED VOLUNTEERS</small><b>{data.volunteers.length}</b></article><article><small>ACTIVE EVENTS</small><b>{data.events.filter(e=>e.status==="ACTIVE").length}</b></article></div><div className="admin-grid"><section className="surface"><CardHead eyebrow="HUMAN REVIEW REQUIRED" title="Reported requests"/><div className="review-list">{data.reports.map(report=><article key={report.id}><div><Badge value={report.status}/><b>{report.request_id} · {human(report.category)}</b><p>{report.reason}</p><small>{report.public_area} · reported {ago(report.created_at)}</small></div><span><button onClick={()=>act({action:"review_report",id:report.id,status:"VERIFIED"},"Report reviewed and request retained")}>Verify</button><button className="danger" onClick={()=>act({action:"review_report",id:report.id,status:"REMOVED"},"Report reviewed and request removed from queue")}>Remove</button></span></article>)}</div></section><section className="surface"><CardHead eyebrow="PARTNER TRUST" title="Organization verification"/><div className="org-list">{data.organizations.map(org=><article key={org.id}><span className="org-avatar">{org.name.slice(0,2).toUpperCase()}</span><div><b>{org.name}</b><small>{org.public_area} · {org.contact_email}</small></div><Badge value={org.verified?"VERIFIED":"PENDING"}/><button className="soft-btn" onClick={()=>act({action:"verify_org",id:org.id,verified:!org.verified},org.verified?"Verification paused":"Organization verified")}>{org.verified?"Review":"Verify"}</button></article>)}</div></section><section className="surface events-card"><CardHead eyebrow="DISASTER EVENTS" title="Event lifecycle"/><div className="event-list">{data.events.map(event=><article key={event.id}><Badge value={event.status}/><div><b>{event.name}</b><small>{JSON.parse(event.affected_areas).join(" · ")}</small></div><time>{new Date(event.starts_at).toLocaleDateString()}</time></article>)}</div></section><Activity items={data.activity}/></div>{showEvent&&<CreateEvent close={()=>setShowEvent(false)} submit={async(payload)=>{const result=await act({action:"create_event",...payload},"Disaster event created");if(result)setShowEvent(false)}}/>}</>}

function Activity({items}:{items:Row[]}){return <section className="surface"><CardHead eyebrow="COORDINATION LOG" title="Live activity"/><div className="activity-list">{items.slice(0,6).map((item,index)=><article key={item.id||index}><i>{item.status==="RESOLVED"?"✓":"↗"}</i><p><b>{item.request_id}</b> · {item.body}<small>{ago(item.created_at)}</small></p></article>)}</div></section>}
function NotificationsView({items,read}:{items:Row[];read:()=>void}){return <><PageHead eyebrow="IN-APP ALERTS" title="Notification center" description="Assignments, status changes, resolutions, and important disaster updates in one place." action={<button className="soft-btn" onClick={read}>Mark all read</button>}/><section className="surface notification-page">{items.map(item=><article className={item.read_at?"read":""} key={item.id}><i>{item.type==="ALERT"?"!":item.type==="STATUS"?"↗":"✓"}</i><div><b>{item.title}</b><p>{item.body}</p><small>{ago(item.created_at)}</small></div>{!item.read_at&&<span>NEW</span>}</article>)}</section></>}
function NotificationPanel({items,close,read}:{items:Row[];close:()=>void;read:()=>void}){return <aside className="notification-panel"><header><h3>Notifications</h3><button onClick={close}>×</button></header>{items.slice(0,5).map(item=><article key={item.id}><i>{item.type==="ALERT"?"!":"✓"}</i><div><b>{item.title}</b><p>{item.body}</p><small>{ago(item.created_at)}</small></div></article>)}<button className="mark-read" onClick={read}>Mark all as read</button></aside>}
function Profile({user,role}:{user:Row;role:string}){return <><PageHead eyebrow="ACCOUNT & PRIVACY" title="Profile settings" description="Manage your operational identity, safety preferences, and account access."/><div className="profile-layout"><section className="surface profile-card"><span className="large-avatar">{(user.name||"AK").split(" ").map((p:string)=>p[0]).join("").slice(0,2)}</span><h2>{user.name}</h2><p>{user.email}</p><Badge value={role.toUpperCase()}/><a className="soft-btn" href="/signout-with-chatgpt?return_to=/">Sign out securely</a></section><section className="surface settings-card"><CardHead eyebrow="SAFETY DEFAULTS" title="Privacy and notifications"/><label htmlFor="privacy-location"><span><b>Hide exact location publicly</b><small>Only an approximate service area is shown on maps.</small></span><input id="privacy-location" aria-label="Hide exact location publicly" type="checkbox" checked readOnly/></label><label htmlFor="assignment-notifications"><span><b>Assignment notifications</b><small>Receive an alert whenever a responder is assigned.</small></span><input id="assignment-notifications" aria-label="Assignment notifications" type="checkbox" defaultChecked/></label><label htmlFor="critical-alerts"><span><b>Critical event alerts</b><small>Important official disaster information appears in-app.</small></span><input id="critical-alerts" aria-label="Critical event alerts" type="checkbox" defaultChecked/></label><div className="security-note">Account authentication is handled by secure workspace sign-in. Operational permissions are checked again for every protected server action.</div></section></div></>}

function RequestModal({events,close,submit}:{events:Row[];close:()=>void;submit:(p:Row,file?:File)=>Promise<void>}){const [busy,setBusy]=useState(false);async function onSubmit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const f=new FormData(event.currentTarget);const candidate=f.get("image");const file=candidate instanceof File?candidate:undefined;f.delete("image");await submit(Object.fromEntries(f),file);setBusy(false)}return <div className="overlay" onMouseDown={close}><section className="modal request-form" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><header><div><p className="overline">EMERGENCY ASSISTANCE</p><h2>Tell us what you need</h2><p>Share only what responders need. Exact contact details remain protected.</p></div><button onClick={close}>×</button></header><form onSubmit={onSubmit}><label>Help category<select name="category" required defaultValue=""><option value="" disabled>Select category</option>{categories.slice(1).map(v=><option key={v} value={v}>{human(v)}</option>)}</select></label><label>General area<input name="publicArea" required minLength={2} placeholder="e.g. Whitefield"/></label><label>People needing help<input name="peopleCount" required type="number" min="1" max="1000"/></label><label>Disaster event<select name="eventId">{events.filter(e=>e.status==="ACTIVE").map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><fieldset><legend>Urgency</legend>{["NORMAL","URGENT","CRITICAL"].map((v,i)=><label key={v}><input type="radio" name="urgency" value={v} defaultChecked={i===0}/>{human(v)}</label>)}</fieldset><label>Preferred contact<select name="contactMethod"><option value="IN_APP">In-app message</option><option value="PHONE">Phone after assignment</option><option value="SMS">SMS after assignment</option></select></label><label className="wide">Short description<textarea name="description" required minLength={10} maxLength={1000} placeholder="Describe the immediate need and any safety concerns…"/></label><label className="wide">Optional image (JPG, PNG, or WebP · max 5 MB)<input name="image" type="file" accept="image/jpeg,image/png,image/webp"/></label><div className="privacy-copy wide">⌾ Your exact address and contact information are never exposed on the public map.</div><div className="modal-actions wide"><button type="button" className="soft-btn" onClick={close}>Cancel</button><button disabled={busy} className="solid-btn">{busy?"Creating safely…":"Create secure request →"}</button></div></form></section></div>}

function RequestDetail({item,data,close,act}:{item:Row;data:State;close:()=>void;act:(p:Row,s:string)=>Promise<any>}){const [note,setNote]=useState("");const assigned=data.volunteers.find(v=>v.user_id===item.assigned_volunteer_id);return <div className="overlay right" onMouseDown={close}><section className="detail-drawer" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><header><div><p className="overline">REQUEST DETAILS</p><h2>{item.id}</h2></div><button onClick={close}>×</button></header><div className="detail-body"><div className="detail-badges"><Badge value={item.urgency}/><Badge value={item.status}/></div><h3>{human(item.category)} assistance</h3><p className="description">{item.description}</p><dl><div><dt>Approximate area</dt><dd>{item.public_area}</dd></div><div><dt>People needing help</dt><dd>{item.people_count}</dd></div><div><dt>Created</dt><dd>{new Date(item.created_at).toLocaleString()}</dd></div><div><dt>Assigned volunteer</dt><dd>{assigned?.name||"Not assigned"}</dd></div></dl><div className="privacy-copy">⌾ Exact contact and address details remain protected until verified assignment.</div><h4>Status timeline</h4><div className="status-timeline">{statuses.slice(0,5).map((value,index)=>{const current=statuses.indexOf(item.status);return <div className={index<=current?"done":""} key={value}><i>{index<current?"✓":index+1}</i><span><b>{human(value)}</b><small>{index<=current?index===current?`Current · ${ago(item.updated_at)}`:"Completed":"Pending"}</small></span></div>})}</div><h4>Post safe progress update</h4><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="e.g. Supplies are being delivered…"/><div className="detail-actions"><select defaultValue={item.status} onChange={e=>act({action:"update_status",id:item.id,status:e.target.value,note},`${item.id} status updated`)}>{statuses.map(value=><option key={value}>{value}</option>)}</select>{item.status==="OPEN"&&<button className="solid-btn" onClick={()=>act({action:"accept_request",id:item.id},`${item.id} accepted`)}>Accept request</button>}<button className="soft-btn danger-text" onClick={()=>act({action:"report",id:item.id,reason:"Submitted for human review from request details"},"Request sent for human review")}>Report concern</button></div></div></section></div>}

function AdjustResource({item,close,submit}:{item:Row;close:()=>void;submit:(delta:number,note:string)=>Promise<void>}){const [delta,setDelta]=useState(0);const [note,setNote]=useState("");return <div className="overlay" onMouseDown={close}><section className="modal compact" onMouseDown={e=>e.stopPropagation()}><header><div><p className="overline">RESOURCE LEDGER</p><h2>Adjust {item.name}</h2><p>{item.quantity.toLocaleString()} {item.unit} currently available</p></div><button onClick={close}>×</button></header><div className="adjust-form"><label>Quantity change<input type="number" value={delta} onChange={e=>setDelta(Number(e.target.value))} placeholder="Use -50 for distribution"/></label><label>Reason<input value={note} onChange={e=>setNote(e.target.value)} placeholder="e.g. Distributed at Bellandur hub"/></label><div className="projected">Projected balance <b>{item.quantity+delta} {item.unit}</b></div><div className="modal-actions"><button className="soft-btn" onClick={close}>Cancel</button><button className="solid-btn" disabled={!delta||!note||item.quantity+delta<0} onClick={()=>submit(delta,note)}>Record transaction</button></div></div></section></div>}
function AddResource({close,submit}:{close:()=>void;submit:(payload:Row)=>Promise<void>}){return <div className="overlay" onMouseDown={close}><section className="modal compact" onMouseDown={e=>e.stopPropagation()}><header><div><p className="overline">NEW INVENTORY</p><h2>Add relief resource</h2><p>Start a non-negative stock ledger for an available supply.</p></div><button onClick={close}>×</button></header><form className="adjust-form" onSubmit={e=>{e.preventDefault();submit(Object.fromEntries(new FormData(e.currentTarget)))}}><label>Resource name<input name="name" required minLength={2} placeholder="e.g. Hygiene kits"/></label><label>Category<select name="category">{categories.slice(1).map(v=><option key={v}>{v}</option>)}</select></label><label>Starting quantity<input name="quantity" type="number" min="0" required/></label><label>Unit<input name="unit" required placeholder="kits, meals, bottles…"/></label><div className="modal-actions"><button type="button" className="soft-btn" onClick={close}>Cancel</button><button className="solid-btn">Add resource</button></div></form></section></div>}
function CreateEvent({close,submit}:{close:()=>void;submit:(payload:Row)=>Promise<void>}){return <div className="overlay" onMouseDown={close}><section className="modal compact" onMouseDown={e=>e.stopPropagation()}><header><div><p className="overline">DISASTER EVENT</p><h2>Create response event</h2><p>Group related requests, areas, partners, and resources.</p></div><button onClick={close}>×</button></header><form className="adjust-form" onSubmit={e=>{e.preventDefault();submit(Object.fromEntries(new FormData(e.currentTarget)))}}><label>Event name<input name="name" required minLength={3} placeholder="e.g. Bengaluru Flood Response"/></label><label>Affected areas<input name="areas" required placeholder="Whitefield, Bellandur, Marathahalli"/></label><div className="privacy-copy">Creating an event does not automatically label any resident or request as fraudulent or unsafe.</div><div className="modal-actions"><button type="button" className="soft-btn" onClick={close}>Cancel</button><button className="solid-btn">Create active event</button></div></form></section></div>}
function Empty({title,text}:{title:string;text:string}){return <div className="empty-state"><span>◎</span><b>{title}</b><p>{text}</p></div>}
