import { integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const users = sqliteTable("users", { id:text("id").primaryKey(), email:text("email").notNull(), name:text("name").notNull(), role:text("role").notNull().default("ADMIN"), emailVerified:integer("email_verified",{mode:"boolean"}).notNull().default(true), blockedAt:text("blocked_at"), createdAt:text("created_at").notNull() }, (table)=>[uniqueIndex("idx_users_email").on(table.email)]);
export const disasterEvents = sqliteTable("disaster_events", { id:text("id").primaryKey(), name:text("name").notNull(), status:text("status").notNull(), affectedAreas:text("affected_areas").notNull(), startsAt:text("starts_at").notNull(), createdAt:text("created_at").notNull() });
export const helpRequests = sqliteTable("help_requests", { id:text("id").primaryKey(), requesterId:text("requester_id").notNull(), eventId:text("event_id"), category:text("category").notNull(), publicArea:text("public_area").notNull(), peopleCount:integer("people_count").notNull(), description:text("description").notNull(), urgency:text("urgency").notNull(), contactMethod:text("contact_method").notNull(), status:text("status").notNull().default("OPEN"), acceptedBy:text("accepted_by"), assignedVolunteerId:text("assigned_volunteer_id"), imageKey:text("image_key"), approxLat:real("approx_lat"), approxLng:real("approx_lng"), helperLat:real("helper_lat"), helperLng:real("helper_lng"), etaMinutes:integer("eta_minutes"), deliveryStartedAt:text("delivery_started_at"), deliveryUpdatedAt:text("delivery_updated_at"), createdAt:text("created_at").notNull(), updatedAt:text("updated_at").notNull() });
export const requestUpdates = sqliteTable("request_updates", { id:integer("id").primaryKey({autoIncrement:true}), requestId:text("request_id").notNull(), authorId:text("author_id").notNull(), status:text("status"), body:text("body").notNull(), createdAt:text("created_at").notNull() });
export const helpOffers = sqliteTable("help_offers", { id:text("id").primaryKey(), requestId:text("request_id").notNull(), helperId:text("helper_id").notNull(), message:text("message").notNull(), status:text("status").notNull().default("PENDING"), createdAt:text("created_at").notNull(), updatedAt:text("updated_at").notNull() }, (table)=>[uniqueIndex("idx_offers_request_helper").on(table.requestId,table.helperId)]);
export const volunteers = sqliteTable("volunteers", { userId:text("user_id").primaryKey(), name:text("name").notNull(), skills:text("skills").notNull(), areas:text("areas").notNull(), available:integer("available",{mode:"boolean"}).notNull().default(true), completedTasks:integer("completed_tasks").notNull().default(0), updatedAt:text("updated_at").notNull() });
export const organizations = sqliteTable("organizations", { id:text("id").primaryKey(), name:text("name").notNull(), publicArea:text("public_area").notNull(), verified:integer("verified",{mode:"boolean"}).notNull().default(false), contactEmail:text("contact_email").notNull(), createdAt:text("created_at").notNull() });
export const resources = sqliteTable("resources", { id:text("id").primaryKey(), organizationId:text("organization_id").notNull(), eventId:text("event_id"), category:text("category").notNull(), name:text("name").notNull(), quantity:integer("quantity").notNull(), unit:text("unit").notNull(), updatedAt:text("updated_at").notNull() });
export const resourceTransactions = sqliteTable("resource_transactions", { id:integer("id").primaryKey({autoIncrement:true}), resourceId:text("resource_id").notNull(), delta:integer("delta").notNull(), note:text("note").notNull(), actorId:text("actor_id").notNull(), createdAt:text("created_at").notNull() });
export const notifications = sqliteTable("notifications", { id:text("id").primaryKey(), userId:text("user_id").notNull(), title:text("title").notNull(), body:text("body").notNull(), type:text("type").notNull(), readAt:text("read_at"), createdAt:text("created_at").notNull() });
export const reports = sqliteTable("reports", { id:text("id").primaryKey(), requestId:text("request_id").notNull(), reporterId:text("reporter_id").notNull(), reason:text("reason").notNull(), status:text("status").notNull(), createdAt:text("created_at").notNull(), reviewedAt:text("reviewed_at") });
export const auditLogs = sqliteTable("audit_logs", { id:integer("id").primaryKey({autoIncrement:true}), actorId:text("actor_id").notNull(), action:text("action").notNull(), entityType:text("entity_type").notNull(), entityId:text("entity_id").notNull(), metadata:text("metadata").notNull(), createdAt:text("created_at").notNull() });
